"""biddatetime

Revision ID: 2ff395769329
Revises: 82a1ad59947e
Create Date: 2018-11-09 20:58:03.788563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff395769329'
down_revision = '82a1ad59947e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bids', 'datetime')
    # ### end Alembic commands ###
